<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="SA01_EnableScanners" Id="{d4a6dc07-237b-4bf8-9a63-c8d6dd546a83}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM SA01_EnableScanners
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="SA01_EnableScanners">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>